CREATE TABLE BOARD (
    NUM INT NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PWD VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(50),
    SUBJECT VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(4000) NOT NULL,
    IPADDR VARCHAR(20),
    HITCOUNT INT,
    CREATED DATE,
    CONSTRAINT PK_BOARD_NUM PRIMARY KEY(NUM)
);
